site_name: Boyd Bot (Messenger)
repo_url: https://github.com/ineshbose/boyd_bot_messenger
repo_name: boyd_bot_messenger

nav:
    - Home: index.md
    - app.py: app.md
    - timetable.py: timetable.md
    - services.py: services.md
    - Templates: templates.md

plugins:
    - search

theme:
    name: material